### PR TITLE
Improve compatibility and add group support

### PR DESCRIPTION
**Pull request by opticron**
This fixes some client crashes with the new Hue app (still non-functional and still non-discoverable, but I'm on the way there), makes the number of exposed lights configurable via a call to the class, returns an empty object for scenes queries (this speeds up client querying versus blank responses), and adds group support (except for scene usage, I'm getting there).

On a side note, I do have local experimental code working for discovery with the new Hue app, but it requires tweaks to the SSDP library since the new Hue app requires the message elements in a certain order and requires non-standard elements in the response (hue-bridgeid). I'm working up a more generic patch that will be more likely to go in to the official ESP8266 hardware package, but that will take some time and probably won't be available in the board manager for even longer.

### CODE REVIEW

**Comment by probonopd** [comment]
In the beginning, I used a [local SSDP implementation](https://github.com/probonopd/ESP8266HueEmulator/tree/ad864771635e0dba61872c7050c7f83a780f9908/ESP8266HueEmulator); later switched to the library when it became available in the ESP8266 hardware package.

Maybe we should go back to this?

**Comment by opticron** [comment]
I was thinking about that. I'll probably pull in a local copy of the current ESP8266SSDP library with the tweaks that will eventually go into mainline if that's alright.

**Comment by probonopd** [comment]
Yes, sure. Better than waiting :+1:

**Comment by probonopd** [comment]
Can you make scenes work @opticron? The iOS app doesn't seem to set up a new bridge without this anymore :-(

**Comment by opticron** [comment]
The android app has been that way for a while now. I did some experimentation with scenes a while back as a hack on top of the group support, but it was too different to do it that way properly. It's definitely on my list of things to do in the near term now that I finally have some basic home automation stuff setup.

**Pull request merged**
