### PR TITLE
Refactor implementation details into a separate file

### PR DESCRIPTION
**Pull request by opticron**
This moves the parsing, HTTP handling, and as much non-user-facing code as possible into a separate file to reduce clutter. This also adds the ability to accept CT and XY color coordinates and adds error responses where necessary. This also fixes some crashes that were occurring on unexpected requests.

### CODE REVIEW

**Comment by opticron** [comment]
I'm not sure what the conflicts are that are preventing an easy merge, but if you can figure out what they are I'll fix them.

**Comment by probonopd** [comment]
I just get the message "This branch has conflicts that must be resolved. Use the command line to resolve conflicts before continuing." Can you resolve them? Not sure where the conflicts are coming from since I haven't touched this code in quite a while.

**Comment by opticron** [comment]
I'll do some massaging on the code and see what I can do to make it easily mergable.

**Comment by opticron** [comment]
This should be ready to go now.

**Comment by opticron** [comment]
By the way, you may want to apply everything up to/including bb97daf to your before-opticron-refactor branch as it's all bug fixes and dead code removal. All the actual refactoring occurs in the last 6 patches.

**Pull request merged**
