### PR TITLE
Fix compliation issues

### PR DESCRIPTION
**Pull request by Solmath**
Due to changes in various dependencies (ESP8266core, NeoPixelBus) the project wouldn't compile using platformIO. Also some minor issues that resulted in compiler warnings were fixed.

### CODE REVIEW

**Comment by Solmath** [comment]
Fixes #120

**Comment by probonopd** [comment]
```
In file included from /home/travis/build/probonopd/ESP8266HueEmulator/ESP8266HueEmulator/ESP8266HueEmulator.ino:11:0:
/home/travis/arduino_ide/libraries/NtpClient/src/NtpClientLib.h:105:25: fatal error: ESPAsyncUDP.h: No such file or directory
 #include <ESPAsyncUDP.h>
```

**Comment by probonopd** [comment]
Also, we should fix the very commit of each library using `git clone -o <hash>` in `.travis.yml` so that things don't break again when libraries change over time. Like we do in https://github.com/probonopd/WirelessPrinting/blob/master/.travis.yml.

**Comment by Solmath** [comment]
> 
> 
> ```
> In file included from /home/travis/build/probonopd/ESP8266HueEmulator/ESP8266HueEmulator/ESP8266HueEmulator.ino:11:0:
> /home/travis/arduino_ide/libraries/NtpClient/src/NtpClientLib.h:105:25: fatal error: ESPAsyncUDP.h: No such file or directory
>  #include <ESPAsyncUDP.h>
> ```

Sorry, I forgot to mention that I included ESPAsyncUDP library from https://github.com/me-no-dev/ESPAsyncUDP manually, because it doesn't seem to be included in https://github.com/esp8266/Arduino.

So in my lib folder I now have aJson, ESPAsyncUDP, NtpClient and Time.

**Comment by Solmath** [comment]
There's still a problem with the flush() function of aJson that I only fixed locally. Working on it now.

**Comment by Solmath** [comment]
My last commit should have done the trick for ESP8266HueEmulator.ino, but I can't get the Json-Example to compile.

aJson seems not to be supported anymore and the example is not crucial to this project in my opinion.

**Comment by probonopd** [comment]
Please review your PR, I think you have added too many files (including aJSON).

**Comment by Solmath** [comment]
Sorry, major f***up. This commit was not planned to go into the PR at all and should only be in my fork. I guess I wasn't thinking quite straight anymore last night.

I'll move the last commits to a separate branch as soon as I come home tonight and hope this will fix it.

**Comment by Solmath** [comment]
Reset origin/master to the correct commit and created branch platformio for my additional changes.

I promise to use separate branches for PRs in the future, I'm just not really used to the workflow, yet.

**Comment by probonopd** [comment]
Looking better, now we need to make it build...

**Comment by Solmath** [comment]
Skipping the Json_Example.ino now, but the travis build just stops after the aJson example sketches. I guess that's not the expected behaviour.

Does it make sense to build all *.ino files (including examples from libraries), or would it be better to call the arduino build for the main sketch as in the WirelessPrinting repo?

**Comment by probonopd** [comment]
I'd say the main sketch is sufficient, what do you think?

**Comment by Solmath** [comment]
Finally found the time to fix the remaining issues after only eight months (sory about that).

**Comment by probonopd** [comment]
Thank you very much @Solmath

**Comment by Darkpecas** [comment]
``

**Pull request merged**
