### PR TITLE
define to use LightSevice.h as a libary

### PR DESCRIPTION
**Pull request by ChrisHanuta**
a define to prevent double compiling of the headers and a define to exclude the SSDP.H

### CODE REVIEW

**Comment by probonopd** [comment]
Does not compile, please check the errors in the build log and append changes to this pull request until it builds "green". Thanks for your valued contribution.

**Comment by ChrisHanuta** [comment]
The build does not work I have undone all changes and it is always broken.

you'r kidding me

**Comment by probonopd** [comment]
Sorry for the trouble @ChrisHanuta - possibly something has changed in the build system at https://github.com/adafruit/travis-ci-arduino since our last successful build at https://travis-ci.org/probonopd/ESP8266HueEmulator/builds/307104499

**Comment by probonopd** [comment]
Trying to revive builds at https://github.com/probonopd/ESP8266HueEmulator/pull/112 - once it is working again, please reopen

**Pull request closed without merging**
