### PR TITLE
Sync the time via NTP and use then data in the config.

### PR DESCRIPTION
**Pull request by ensonic**
I've installed the libraries via the library manager in the arduino IDE, but I can can also try to patch the README.md to git clone them like you did for the other libs.
Installing them though the library manager has the advantage that one can also update them that way.

### CODE REVIEW

**Comment by ensonic** [comment]
@probonopd will add the 2 git clone commands to travis.yml + README tonight.

**Comment by probonopd** [comment]
Thank you for this valuable contribution. How will this behave if the NTP server is unreachable?

**Comment by ensonic** [comment]
The time on the esp starts counting from 0, so if we have not synced, we send a wrong time. This is not much worse than no time, but I can send another PR to check if we have a time already and only add the fields to the config message in that case.

**Comment by probonopd** [comment]
That'd be great!

**Comment by ensonic** [comment]
Done. https://github.com/probonopd/ESP8266HueEmulator/pull/72

**Pull request merged**
